#!/usr/bin/env bash

audio-switch() {
	echo "$(tput setaf 1)===============
 Sound Devices
===============$(tput bold)$(tput setaf 3)"
	pacmd list-sinks | sed '/sink/!d'
	echo "$(tput bold)$(tput setaf 2)"
	pacmd list-sinks | \
	sed '/index\|long_card_name/!d;s/^.*= "/		/;s/ at .*$//;s/index/Device/'
	read -r -p "$(tput setaf 4)
	Pick a Device: " n
	tput sgr0
	# list all apps in playback tab (ex: cmus, mplayer, vlc)
	inputs=($(pacmd list-sink-inputs | sed '/index/!d;s/^.*: //'))
	# set the default output device
	pacmd set-default-sink "$n" &> /dev/null
	# apply the changes to all running apps to use the new output device
	for i in ${inputs[*]}; do pacmd move-sink-input "$i" "$n" &> /dev/null; done
	}
audio-switch-app() {
	# list individual apps
	echo "$(tput bold)$(tput setaf 1)===============
 Running Apps
===============$(tput bold)$(tput setaf 3)"
	pacmd list-sink-inputs | sed '/sink input/!d'
	echo "$(tput bold)$(tput setaf 2)"
	pacmd list-sink-inputs | \
	sed '/index\|application.name =/!d;s/^.*= "/		/;s/".*$//;s/index/App/'
	# list all sound device
	echo "$(tput setaf 1)===============
 Sound Devices
===============$(tput bold)$(tput setaf 3)"
	pacmd list-sinks | sed -n '/sink/p'
	echo "$(tput bold)$(tput setaf 2)"
	pacmd list-sinks | \
	sed '/index\|long_card_name/!d;s/^.*= "/		/;s/ at .*$//;s/index/Device/'
	read -r -p "$(tput setaf 4)
	Pick a App: " app
	read -r -p "$(tput setaf 4)
	Pick a Device: " device
	tput sgr0
	# set the default output device
	pacmd set-default-sink "$device" &> /dev/null
	# apply changes to one running app to use the new output device
	pacmd move-sink-input "$app" "$device" &> /dev/null
	}
Menu(){
	echo "$(tput bold)$(tput setaf 1)===============
 Audio-Switch
===============$(tput setaf 3)

	1) $(tput setaf 2)Change audio output device.$(tput setaf 3)

	2) $(tput setaf 2)Change audio output of an application.$(tput setaf 3)

	q) $(tput setaf 2)Exit.$(tput setaf 4)
	"
	read -r -p "Opção: " Resposta

	case "$Resposta" in
		1)
			audio-switch
			clear
			Menu;;
		2)
			audio-switch-app
			clear
			Menu;;
		q) exit ;;
		*)
			clear
			echo "$(tput setaf 1)==================
Unknown option(s).
==================

$(tput sgr0)"
		Menu ;;
    esac
	}
clear
Menu
