#!/usr/bin/env bash

Bookmarks=~/.favoritos
Browser="firefox"
Search='https://duckduckgo.com/?q='
FzfOpt='fzf -e --border -i --print-query --margin=20% --tiebreak=begin --prompt=Bookmarks:'

# Pegar favoritos do Firefox Automaticamente.
#
# Abra o Firefox e digite na barra de endereço "about:config".
# Pesquise por "browser.bookmarks.autoExportHTML" mude para "true".
# Pesquise por "browser.bookmarks.file" escolha texto e adicione "~/.favoritos".
#

Site=$(sed -r '/http/!d;s/^.*HREF="(.*)" ADD_DATE=.*">(.*)<\/A>.*$/\2𤭢┃\"\1\"/' $Bookmarks \
  | column -t -s "𤭢" \
  | $FzfOpt \
  | sed 's/#Porn.*┃\|#Hentai.*┃/┃--private-window /' \
  | sed 's/^.*┃//;/^$/d')

if [ -n "$Site" ]; then
    if grep '^"http' <<< "$Site"; then
      eval $Browser "$Site" &
    else
      eval $Browser "\"$Search$Site\"" &
    fi
fi
