#!/usr/bin/env bash

Pesquisador='https://duckduckgo.com/?q='
Favoritos=~/.favoritos
Navegador="firefox"
FzfOpt='fzf -e --border -i --print-query --margin=20% --tiebreak=begin --prompt=Bookmarks:'

# Pegar favoritos do Firefox Automaticamente.
#
# Abra o Firefox e digite na barra de endereço "about:config".
# Pesquise por "browser.bookmarks.autoExportHTML" mude para "true".
# Pesquise por "browser.bookmarks.file" escolha texto e adicione "~/.favoritos".
#

Resposta=$(sed -r '/http/!d;s/^.*HREF="(.*)" ADD_DATE=.*">(.*)<\/A>.*$/\2𤭢┃\"\1\"/' $Favoritos \
  | column -t -s "𤭢" \
  | $FzfOpt \
  | sed 's/#Porn.*┃\|#Hentai.*┃/┃--private-window /' \
  | sed 's/^.*┃//;/^$/d')

if [ -n "$Resposta" ]; then
    if grep '"http' <<< "$Resposta" >/dev/null; then
      Favorito=$(sed '/"http/!d' <<< "$Resposta")
      eval $Navegador "$Favorito" &
    else
      eval $Navegador "\"$Pesquisador$Resposta\"" &
    fi
fi
