#!/usr/bin/env bash

# Styles...
RCor="$(tput setaf 1)"
bold="$(tput bold)"
reset="$(tput sgr0)"

# Include 'os-release' to grab Debian pretty name...
. /etc/os-release

Dpkg=$(command -v dpkg 1>/dev/null && dpkg-query --list | sed '/^ii /!d' | wc -l | sed 's/.*/ & \(dpkg\)/')
Flatpak=$(command -v flatpak 1>/dev/null && flatpak list | sed '1d' | wc -l | sed 's/.*/, & \(flatpak\)/')
Snap=$(command -v snap 1>/dev/null && snap list | sed '1d' | wc -l | sed 's/.*/, & \(snap\)/')
Memory=$(free -h | awk 'NR==2{printf "%s/%s (%.2f%%)\n", $3,$2,$3*100/$2}')
DiskRoot=$(df -h | awk '$NF=="/"{printf "%s/%s (%s)\n", $3,$2,$5}')
DiskHome=$(df -h | awk '$NF=="/home"{printf "%s/%s (%s)\n", $3,$2,$5}')

# Main...
clear

echo "
$RCor            ⢀⣴⠾⠻⢶⣦⠀
$RCor            ⣾⠁⢠⠒⠀⣿⡁
$RCor            ⢿⡄⠘⠷⠚⠋⠀
$RCor            ⠈⠳⣄⠀⠀⠀⠀$reset

${bold} $PRETTY_NAME${reset}
${bold} Kernel:${reset} $(uname -rm)
${bold} Memory:$reset $Memory${reset}
${bold} Uptime:${reset} $(uptime -p | cut -d' ' -f2-)
${bold} Packages:$reset$Dpkg$Flatpak$Snap${reset}"
exit 0
