#!/usr/bin/env bash

Destino="$2"
Conteudo=$(wget -qO- "m.${1#*//}")

Nome=$(sed -r '/title/!d;s/.*title>(.*)<\/.*$/\1/' <<< "$Conteudo" | sed -r 's/.*<\/div>(.*)<\/div>/\1/' | sed '/^</d' | sed ':a;$!N;s/\n//;ta;')
Paginas=$(sed -r '/<option/!d;s/^.*"\/\/(.*)".*$/\1/' <<< "$Conteudo")

for Pagina in $Paginas
do
  Conteudo=$(wget -qO- "$Pagina")
  Link=$(sed -r '/^<img src/!d;s/.*"\/\/(.*)" style.*$/\1/' <<< "$Conteudo")
  NPagina=$(sed -r 's/.*\/(.*).html/\1/' <<< "$Pagina" | sed -e 's/\([0-9]\)/00\1/;s/0*\(...\)/\1.jpg/')
  mkdir "$Nome"
  wget -c "$Link" -O "$Nome/$NPagina"
done

if [ -z "$Destino" ]; then
  zip -rm "$Nome".cbz "$Nome"
else
  zip -rm "$Destino/$Nome".cbz "$Nome"
fi
