#!/usr/bin/env bash

Destino="$2"
Conteudo=$(wget -qO- "m.${1#*//}")

Nome=$(sed -r '/title/!d
  s/.*title>(.*)<\/.*$/\1/
  ;:a;$!N;s/\n//;ta;
  s/<.*data-share="false"><\/div>(.*)<\/div><a .*$/\1/' <<< "$Conteudo")
Paginas=$(sed -r '/<option/!d
  s/^.*"\/\/(.*)".*$/\1/' <<< "$Conteudo")

for Pagina in $Paginas
do
  Conteudo=$(wget -qO- "$Pagina")
  Link=$(sed -r '/^<img src/!d
    s/.*"\/\/(.*)" style.*$/\1/' <<< "$Conteudo")
  NPagina=$(sed -r 's/^.*\/([0-9]*)\.html/00\1/
    s/0*(...)/\1.jpg/' <<< "$Pagina")
  mkdir "/tmp/$Nome" 2> /dev/null
  wget -cq "$Link" -O "/tmp/$Nome/$NPagina"
  echo -e "\033[1;31m[\033[1;37m${NPagina%%.*}/0$(wc -l <<< $Paginas)\033[1;31m] \033[1;34m$Nome"
done

if [ -z "$Destino" ]; then
  zip -rmq "$Nome".cbz "/tmp/$Nome"
else
  zip -rmq "$Destino/$Nome".cbz "/tmp/$Nome"
fi
