#!/usr/bin/env bash

###############################################################################

#     _    _
#    / \  | | __ _ _ __  _ __      Alann Santos
#   / _ \ | |/ _` | '_ \| '_ \     https://github.com/alannssantos
#  / ___ \| | (_| | | | | | | |
# /_/   \_\_|\__,_|_| |_|_| |_|

Opcoes=$(lsblk -o "FSTYPE,PATH,SIZE,FSTYPE,LABEL,RM,MOUNTPOINT" \
	| sed '/^ /d' \
	| sed 's|^.*/dev/|/dev/|' \
	| sed '/sd./!d;s/ 0 / \(Disco Local\)𤭢/;s/ 1 / \(Disco Removível\)𤭢/' \
	| column -t -s "𤭢")

Escolha=$(echo " Escolha a Partição que deve ser Montada ou Desmontada.

$Opcoes

 Sair" | fzf -e --layout=reverse-list --color='fg:#99cc99,fg+:#2d2d2d,bg+:#99cc99,pointer:#2d2d2d,prompt:#99cc99' --margin=5% --border --no-info --phony | sed 's/ .*$//')

udisksctl mount -b $Escolha $1 2>/dev/null || udisksctl unmount -b $Escolha $1 2>/dev/null
