#!/usr/bin/env bash

#     _    _
#    / \  | | __ _ _ __  _ __      Alann Santos
#   / _ \ | |/ _` | '_ \| '_ \     https://github.com/alannssantos
#  / ___ \| | (_| | | | | | | |
# /_/   \_\_|\__,_|_| |_|_| |_|

# Varialvel de Client Torrent.
Programa="transmission-remote -a"
#Programa="qbittorrent --skip-dialog=true --sequential"

# O site que vai ser usado.
Site="https://nyaa.si/?f=2&c=1_2&q="

# Tratando a pesquisa.
Pesquisa="$*"

# Definindo se vai pesquisar ou olhar o top 100.
if [ -z "$Pesquisa" ] ; then
	Url="$Site&s=seeders&o=desc"
else
	Url="$Site$Pesquisa&s=seeders&o=desc"
fi

Resultados=$(wget -qO- "$Url" \
	| sed -r '/\/view\/[0-9]*\"|magnet\"|class=\"text-center\">[0-9]/!d;s/^.*title="(.*)">.*$/\1/' \
	| sed -r 's/^.*<a href="(.*)"><i class=.*$/\1/;s/^.*text-center\">(.*)<\/td>.*$/\1/' \
	| sed 'N;N;N;N;N;s!\n!┃!g' \
	| awk -F '┃' '{print "💾"$3 "𤭢"$1 "𤭢🌱"$4 "𤭢🔽"$5 "𤭢┃"$2 }' \
	| column -t -s "𤭢" \
	| fzf -e -m --color=16 --border \
	| sed 's/^.*┃//')

if [ ! -z "$Resultados" ]; then
	for Resultado in $Resultados
		do
			$Programa "$Resultado"
		done
fi
