#!/usr/bin/env bash

Destino="$2"
Conteudo=$(wget -qO- "$1")

Nome=$(sed -r '/Current Issue:/!d
  s/^.*">(.*)<\/a.*$/\1/' <<< "$Conteudo")
Paginas=$(sed -r '/<img class="img-responsive"/!d
  s/^.*data-src=. (.*\.jpg|.*\.png) .*$/\1/' <<< "$Conteudo")
TPaginas=$(sed -r '$!d
    s/^.*\/(.*)/00\1/
    s/0*(.......)/\1/' <<< "${Paginas##*/}")

for Pagina in $Paginas
do
  NPagina=$(sed -r 's/^.*\/(.*)/00\1/
    s/0*(.......)/\1/' <<< "$Pagina")
  mkdir "/tmp/$Nome" 2> /dev/null
  wget -cq "$Pagina" -O "/tmp/$Nome/$NPagina"
  echo -e "\033[1;31m[\033[1;37m${NPagina%%.*}/${TPaginas%%.*}\033[1;31m] \033[1;34m$Nome"
done

if [ -z "$Destino" ]; then
  zip -rmq "$Nome".cbz "/tmp/$Nome"
else
  zip -rmq "$Destino/$Nome".cbz "/tmp/$Nome"
fi
