#!/usr/bin/env bash

# Script pra encontrar rss de filmes que vão ser lançados

Link1='https://yts.mx/rss/'
Link2=$(echo "$*" | sed 's/ /%20/g')
Link3='/all/all/0/en'

if [ -z "$Link2" ] ; then
    Search="0"
else
    Search="$Link2"
fi

Final_link=${Link1}${Search}${Link3}

R=$(wget -qO- "$Final_link" \
    | sed '/<title><\!\[CDATA\[/!d;s/^.*<!\[CDATA\[//;s/\]\]><\/title>.*$//'
    )

echo ""
echo "$(tput bold)$(tput setaf 2)${Final_link}"
echo ""
echo "$(tput bold)$(tput setaf 3)${R}"
