#!/usr/bin/env bash

tmux_bar(){
# {{{ #### Transmission
Torrent=$(transmission-remote -l \
  | sed -r '/%|Unknown/!d
    s/.*Verifying.*/⌛️/
    s/.*Seeding.*/🌱/
    s/.*Stopped.*/🔴/
    s/.*100%.*/✅/
    s/.*Idle.*/⌛️/
    s/.*Unknown.*/❗/
    s/.*Uploading.*/📤/
    s/ .* (.*%).*Up & Down.*/📥[\1]/
    s/ .* (.*%).*Downloading.*/📥[\1]/' \
  | sort \
  | uniq -c \
  | sed -r 's/ //g
    s/(.*🔴.*)/#[fg=colour1] \1/
    s/(.*❗.*)/#[fg=colour5] \1/
    s/(.*⌛️.*)/#[fg=colour11] \1/
    s/(.*🌱.*)/#[fg=colour71] \1/
    s/(.*✅.*)/#[fg=colour71] \1/
    s/(.*📤.*)/#[fg=colour71] \1/
    s/.*(📥.*$)/#[fg=colour4] \1/' \
  | sed ':a;$!N;s/\n//;ta;' \
  | sed 's/^/ #[fg=colour71]┃/')
echo -n "$Torrent"
#### ━━━━━━━━━━━━ # }}}
# {{{ #### Mpc Player
Player=$(mpc -f "[[%artist% ┃ ]%title%]|[%file$]" 2>/dev/null \
  | sed -r '/^volume:|^\[playing\]|^\[paused\]/d
    s/(.* )┃( .*)/ #[fg=colour71]┃ 🎵 \1-#[fg=colour5]\2/')
echo -n "$Player"
#### ━━━━━━━━━━ # }}}
# {{{ #### Temperatura CPU
Temp=$(sensors | sed -r '/Package id 0:/!d;s/.*\+(.*)\..°C *\(.*$/ #[fg=colour71]┃ \1°C/')
echo -n "$Temp"
#### ━━━━━━━━━━━━━━━ # }}}
}

tmux_bar
