#!/usr/bin/env bash

# Copyright (c) 2019 Alann Santos

# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:

# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.

# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.

###############################################################################

#     _    _
#    / \  | | __ _ _ __  _ __      Alann Santos
#   / _ \ | |/ _` | '_ \| '_ \     https://gitlab.com/alannssantos
#  / ___ \| | (_| | | | | | | |
# /_/   \_\_|\__,_|_| |_|_| |_|

#### Variaveis.
## Cores.
RCor="\033[1;31m"    # Red (Vermelho)
GCor="\033[1;32m"    # Green (Verde)
YCor="\033[1;33m"    # Yellow (Amarelo)
BCor="\033[1;34m"    # Blue (Azul)
WCor="\033[1;37m"    # White (Branco)
ECor="\033[0m"       # End (Fim)
## Data (parte do nome do arquivo).
data=$(date +"%m-%d-%Y_%H:%M:%S")

clear; echo -e "
    $YCor╔══════════════════════════════╗$ECor
    $YCor║$BCor Editor de Video Simples v0.1$ECor $YCor║$ECor
    $YCor╠══════════════════════════════╣$ECor
    $YCor║                              ║$ECor
    $YCor║      $BCor 1$WCor)$GCor Gravar WebCam$ECor       $YCor║$ECor
    $YCor║     $BCor 2$WCor)$GCor Combinar Videos$ECor      $YCor║$ECor
    $YCor║    $BCor 3$WCor)$GCor Efeito time lapse$ECor     $YCor║$ECor
    $YCor║                              ║$ECor
    $YCor╚══════════════════════════════╝$ECor"

read -r n
case $n in
  1) clear;
        ffmpeg -video_size 1280x720 -i /dev/video0 Captura_de_webcam_"$data".mkv;;
  2) clear;
        for f in ./*.mkv; do echo "file '$f'" >> mylist.txt; done
            ffmpeg -f concat -safe 0 -i mylist.txt -c copy All_For_One_"$data".mkv
            echo -e "$RCor$(cat mylist.txt)$ECor"
            rm mylist.txt
            ;;
  3) clear;
        echo -e "
         $YCor╔════════════════╗$ECor 
         $YCor║$BCor   Velocidade$ECor   $YCor║$ECor
         $YCor╠════════════════╣$ECor
         $YCor║    $BCor 1$WCor)$GCor 2x      $YCor║$ECor
         $YCor║    $BCor 2$WCor)$GCor 4x      $YCor║$ECor
         $YCor║    $BCor 3$WCor)$GCor 8x      $YCor║$ECor
         $YCor╚════════════════╝$ECor"

    read -r speed
    case $speed in
        1) clear;
        ffmpeg -i ./All_For_One*.mkv -r 60 -filter:v "setpts=0.5*PTS" Speed2x_"$data".mkv
        echo -e "\n$RCor Velocidade 2x $ECor"
        ;;
        2) clear;
        ffmpeg -i ./All_For_One*.mkv -r 60 -filter:v "setpts=0.25*PTS" Speed4x_"$data".mkv
        echo -e "\n$RCor Velocidade 4x $ECor"
        ;;
        3) clear;
        ffmpeg -i ./All_For_One*.mkv -r 60 -filter:v "setpts=0.13*PTS" Speed8x_"$data".mkv
        echo -e "\n$RCor Velocidade 8x $ECor"
        ;; 
        *) clear; echo -e "
      $YCor╔══════════════════════════════════╗$ECor
      $YCor║        $RCor Opção Inválida $ECor          $YCor║
      $YCor╚══════════════════════════════════╝$ECor";;
    esac
        ;;
  *) clear; echo -e "
 $YCor╔══════════════════════════════════╗$ECor
 $YCor║        $RCor Opção Inválida $ECor          $YCor║
 $YCor╚══════════════════════════════════╝$ECor";;
esac