#!/bin/env bash

#     _    _
#    / \  | | __ _ _ __  _ __      Alann Santos
#   / _ \ | |/ _` | '_ \| '_ \     https://github.com/alannssantos
#  / ___ \| | (_| | | | | | | |
# /_/   \_\_|\__,_|_| |_|_| |_|

# Varialvel de Client Torrent.
Programa="transmission-remote -a"
#Programa="qbittorrent --skip-dialog=true --sequential"

# O site que vai ser usado.
Site="https://yts.mx"

# Tratando a pesquisa.
Pesquisa="$*"

if [ -z "$Pesquisa" ]; then
	Url="$Site/browse-movies/0/all/all/0/featured/0/all"
else
	Url="$Site/browse-movies/$Pesquisa/all/all/0/latest/0/all"
fi

Resultado=$(wget -qO- "$Url" \
	| sed '/class="browse-movie-link"\|img class="img-responsive"/!d' \
	| sed -r 's/^.*<a href="(.*)" .*$/\1/;s/^.*alt="(.*) download".*$/\1/' \
	| sed 'N;s/\n/𤭢/' \
	| sed -r 's/(.*)𤭢(.*)/\2𤭢┃\1/' \
	| column -t -s "𤭢" \
	| fzf -e --border --prompt=YTS.MX: \
	| sed 's/^.*┃//')

if [ -n "$Resultado" ]; then
	Qualidade=$(wget -qO- "$Resultado" \
		| sed -r '/<a href=".*" rel=".*title=".*"><span class=".*<\/a>/!d' \
		| sed -r 's/^.*<a href="(.*)" rel=".*"><\/span>(.*)<\/a>.*$/\2𤭢┃\1/'\
		| column -t -s "𤭢" \
		| fzf -e --border --prompt=Qualidade: \
		| sed 's/^.*┃//')

	if [ -n "$Qualidade" ]; then
		$Programa "$Qualidade"
	fi
fi
