#!/usr/bin/env bash

## Cores.
RCor="\033[1;31m"    # Red (Vermelho)
GCor="\033[1;32m"    # Green (Verde)
YCor="\033[1;33m"    # Yellow (Amarelo)
ECor="\033[0m"       # End (Fim)

Sussesso="$YCor
╭────────────────────────╮
│$GCor Instalado com sucesso!$YCor │
╰────────────────────────╯
$ECor"
Fracasso="$YCor
╭────────────────────────╮
│  $RCor Erro na instalação!$YCor  │
╰────────────────────────╯
$ECor"

sudo apt install python3-pip rofi compton lxappearance qt5ct -y \
  && python3 -m venv "$HOME/.local" \
  && pip3 install xcffib \
  && pip3 install --no-cache-dir cairocffi \
  && pip3 install dbus-next \
  && pip3 install qtile \
  && pip3 install qtile-extras \
  && echo "[Desktop Entry]
Name=Qtile
Comment=Qtile Session
Exec=$(which qtile) start
Type=Application
Keywords=wm;tiling" | sudo tee /usr/share/xsessions/qtile.desktop \
  && echo -e "$Sussesso" || echo -e "$Fracasso"
