#!/usr/bin/env bash

#     _    _
#    / \  | | __ _ _ __  _ __      Alann Santos
#   / _ \ | |/ _` | '_ \| '_ \     https://gitlab.com/alannssantos
#  / ___ \| | (_| | | | | | | |
# /_/   \_\_|\__,_|_| |_|_| |_|

## Cores.
RCor="\033[1;31m"    # Red (Vermelho)
GCor="\033[1;32m"    # Green (Verde)
YCor="\033[1;33m"    # Yellow (Amarelo)
BCor="\033[1;34m"    # Blue (Azul)
WCor="\033[1;37m"    # White (Branco)
ECor="\033[0m"       # End (Fim)

## Mensagens

Sussesso="$YCor
╭────────────────────────╮
│$GCor Instalado com sucesso!$YCor │
╰────────────────────────╯
$ECor"
Fracasso="$YCor
╭────────────────────────╮
│  $RCor Erro na instalação!$YCor  │
╰────────────────────────╯
$ECor"

## Funções
Sistema(){
#### Aplicativos e Drivers Pos-instalação.
sudo apt install mpc \
	mpd \
	mpv \
	npm \
	rar \
	curl \
	lynx \
	peek \
	slop \
	sxiv \
	tmux \
	atool \
	cmake \
	irssi \
	xclip \
	mpg123 \
	xinput \
	blueman \
	gparted \
	ncmpcpp \
	neomutt \
	w3m-img \
	xdotool \
	zathura \
	redshift \
	smplayer \
	arc-theme \
	keepassxc \
	pkg-config \
	streamlink \
	zlib1g-dev \
	python3-pip \
	simple-scan \
	python3-dev \
	libxtst-dev \
	font-manager \
	libgtk-3-dev \
	fonts-firacode \
	xfce4-terminal \
	numix-gtk-theme \
	numix-icon-theme \
	transmission-cli \
	ffmpegthumbnailer \
	papirus-icon-theme \
	python3-libtorrent \
	breeze-cursor-theme \
	libjpeg62-turbo-dev \
	transmission-daemon \
	fonts-noto-color-emoji \
	transmission-remote-cli \
	transmission-remote-gtk \
	numix-icon-theme-circle \
	ttf-mscorefonts-installer -y && \

sudo apt update && \
sudo apt upgrade -y && \
npm config set prefix "$HOME/.local" && \
pip3 install jedi && \
pip3 install flexget && \
pip3 install ueberzug && \
pip3 install ranger-fm && \
pip3 install gallery-dl && \
pip3 install subliminal && \
pip3 install youtube-dl && \
pip3 install PyQt5==5.14.0 && \
pip3 install transmission-rpc && \
pip3 install KindleComicConverter && \
pip3 install git+https://github.com/alannssantos/mangascandl.git && \
echo -e "$BCor\nSistema!$ECor" && \
echo -e "$Sussesso" || \
echo -e "$Fracasso"
}

Bat_Touchegg_NeoVim(){
#### Bat (cat mais bonito.)
url1="https://github.com"
url2=$(wget -qO- "https://github.com/sharkdp/bat/releases" \
	| sed -r '/bat_.*_amd64.deb/!d;s/^.*href="(.*)" rel=.*$/\1/' \
	| sed '1!d')
wget -c "$url1$url2" -P /tmp/ && \
sudo apt install /tmp/bat_*_amd64.deb -y && \
echo -e "$BCor\nInstalacao do Bat!$ECor" && \
echo -e "$Sussesso" || \
echo -e "$Fracasso"

#### Touchegg (mais funções no touchpad.)
url1="https://github.com"
url2=$(wget -qO- "https://github.com/JoseExposito/touchegg/releases" \
	| sed -r '/touchegg_.*_amd64.deb/!d;s/^.*href="(.*)" rel=.*$/\1/' \
	| sed '1!d')
wget -c "$url1$url2" -P /tmp/ && \
sudo apt install /tmp/touchegg_*_amd64.deb -y && \
echo -e "$BCor\nInstalacao do Touchegg!$ECor" && \
echo -e "$Sussesso" || \
echo -e "$Fracasso"

#### NeoVim AppImage.
url1="https://github.com"
url2=$(wget -qO- "https://github.com/neovim/neovim/releases" \
	| sed -r '/\/download\/v[0-9].*nvim.appimage"/!d;s/^.*href="(.*)" rel=.*$/\1/' \
	| sed '1!d')
wget -c "$url1$url2" -O "vim" && \
chmod +x vim && \
sudo mv -v vim /usr/bin/vim && \
echo -e "$BCor\nInstalacao do NeoVim!$ECor" && \
echo -e "$Sussesso" || \
echo -e "$Fracasso"
}

Fzf_Dragon(){
#### Instalação do Fuzzy Finder.
git clone --depth 1 https://github.com/junegunn/fzf.git ~/.config/fzf && ~/.config/fzf/install --all && \
echo -e "$BCor\nInstalacao do Fuzzy Finder$ECor" && \
echo -e "$Sussesso" || \
echo -e "$Fracasso"

#### Dragon (drag and drop pelo terminal).
git clone https://github.com/mwh/dragon.git /tmp/dragon && cd /tmp/dragon && make && make install && \
echo -e "$BCor\nInstalacao do Dragon.$ECor" && \
echo -e "$Sussesso" || \
echo -e "$Fracasso"
}

NerdFonts_RangerIcons(){
#### Nerd Fonts e Ranger config.
mkdir -vp "$HOME/.local/share/fonts/FiraCode"
url1="https://github.com"
url2=$(wget -qO- "https://github.com/ryanoasis/nerd-fonts/releases" \
	| sed -r '/FiraCode.zip/!d;s/^.*href="(.*)" rel=.*$/\1/' \
	| sed '1!d')
wget -c "$url1$url2" -P /tmp/ && \
atool --extract-to="$HOME/.local/share/fonts/FiraCode" /tmp/FiraCode.zip && \
git clone https://github.com/alexanderjeurissen/ranger_devicons ~/.config/ranger/plugins/ranger_devicons && \
echo "default_linemode devicons" >> ~/.config/ranger/rc.conf && \
echo -e "$BCor\nNerd Fonts e Ranger config.$ECor" && \
echo -e "$Sussesso" || \
echo -e "$Fracasso"
}

DockBarX(){
#### DockBarX.
Urls=$(wget -qO- "https://launchpad.net/~xuzhen666/+archive/ubuntu/dockbarx/+packages?field.name_filter=&field.status_filter=published&field.series_filter=bionic" \
	| sed -r '/sprite expander/!d;s/^.*href="(.*)" .*$/https:\/\/launchpad.net\/~xuzhen666\/+archive\/ubuntu\/dockbarx\/\1/' \
	| sed ';:a;$!N;s/\n/ /;ta;')
Links=$(eval wget -qO- "$Urls" \
	| sed '/.deb/!d' \
	| sed -r  's/^.*<a href="(.*.deb)">.*$/\1/' \
	| sed '/dockbarx-common\|dockbarx-themes-extra\|xfce4-dockbarx-plugin.*.amd64/!d' \
	| sed '/.deb$/!d' \
	| sed ';:a;$!N;s/\n/ /;ta;')
eval wget -c "$Links" && \
sudo apt install ./*.deb -y && \
echo -e "$BCor\nInstalacao do DockBarX.$ECor" && \
echo -e "$Sussesso" || \
echo -e "$Fracasso"
}

Configs(){
#### Copiar Dotfiles e Plugins.
cp -r -v .config .irssi .local .bash_aliases .nanorc .tmux.conf .Xresources ~/ && \
echo -e "$BCor\n05.Copiando arquivos de configuração...$ECor" && \
echo -e "$Sussesso" || \
echo -e "$Fracasso"
}

OpInvalido(){
clear
echo -e "$YCor

	╭────────────────────────╮
	│$RCor   Opção desconhecida.$YCor  │
	╰────────────────────────╯
$ECor"
}

Menu(){
echo -e "$BCor
	1.Sistema
	2.Bat, Touchegg e NeoVim
	3.Fuzzy Finder e Dragon
	4.Nerd Fonts e Ranger config $YCor(pode demorar bastante tempo.)$BCor
	5.DockBarX
	6.Configs
$RCor
	q.Sair
$ECor"
read -r Resposta

case "$Resposta" in
	1)
		Sistema
		Menu ;;
	2)
		Bat_Touchegg_NeoVim
		Menu ;;
	3)
		Fzf_Dragon
		Menu ;;
	4)
		NerdFonts_RangerIcons
		Menu ;;
	5)
		DockBarX
		Menu ;;
	6)
		Configs
		Menu ;;
	q)
		exit ;;
	*)
		OpInvalido
		Menu ;;
esac
}
Menu
