#!/usr/bin/env bash

#     _    _
#    / \  | | __ _ _ __  _ __      Alann Santos
#   / _ \ | |/ _` | '_ \| '_ \     https://gitlab.com/alannssantos
#  / ___ \| | (_| | | | | | | |
# /_/   \_\_|\__,_|_| |_|_| |_|

## Cores.
RCor="\033[1;31m"    # Red (Vermelho)
GCor="\033[1;32m"    # Green (Verde)
YCor="\033[1;33m"    # Yellow (Amarelo)
BCor="\033[1;34m"    # Blue (Azul)
WCor="\033[1;37m"    # White (Branco)
ECor="\033[0m"       # End (Fim)

## Mensagens

Sussesso="$YCor
╭────────────────────────╮
│$GCor Instalado com sucesso!$YCor │
╰────────────────────────╯
$ECor"
Fracasso="$YCor
╭────────────────────────╮
│  $RCor Erro na instalação!$YCor  │
╰────────────────────────╯
$ECor"

## Funções
Sistema(){
#### Aplicativos e Drivers Pos-instalação.
sudo apt install feh \
	mpc \
	mpd \
	mpv \
	npm \
	rar \
	cups \
	curl \
	lynx \
	peek \
	slop \
	sxiv \
	tmux \
	aria2 \
	atool \
	cmake \
	irssi \
	sshfs \
	xclip \
	clamav \
	mcomix \
	mpg123 \
	xinput \
	blueman \
	concalc \
	flatpak \
	gparted \
	ncmpcpp \
	w3m-img \
	xdotool \
	zathura \
	redshift \
	smplayer \
	xsensors \
	arc-theme \
	keepassxc \
	pkg-config \
	streamlink \
	zlib1g-dev \
	python3-pip \
	simple-scan \
	python3-dev \
	libxtst-dev \
	font-manager \
	libclamunrar \
	libgtk-3-dev \
	clamav-daemon \
	poppler-utils \
	fonts-firacode \
	network-manager \
	paper-icon-theme \
	libfreetype6-dev \
	libxkbcommon-dev \
	transmission-cli \
	ffmpegthumbnailer \
	libfontconfig1-dev \
	libxcb-xfixes0-dev \
	python3-libtorrent \
	printer-driver-all \
	breeze-cursor-theme \
	libjpeg62-turbo-dev \
	transmission-daemon \
	libimage-exiftool-perl \
	ttf-mscorefonts-installer -y && \

sudo apt update && \
sudo apt upgrade -y && \
sudo rm /var/log/clamav/freshclam.log ; \
sudo freshclam && \
npm config set prefix "$HOME/.local" && \
npm i -g pyright && \
npm i -g bash-language-server && \
pip3 install jedi && \
pip3 install aria2p && \
pip3 install flexget && \
pip3 install ueberzug && \
pip3 install pyperclip && \
pip3 install gallery-dl && \
pip3 install subliminal && \
pip3 install youtube-dl && \
pip3 install PyQt5==5.14.0 && \
pip3 install transmission-rpc && \
pip3 install KindleComicConverter && \
pip3 install python-telegram-bot==12.8 && \
echo -e "$BCor\nSistema!$ECor" && \
echo -e "$Sussesso" || \
echo -e "$Fracasso"
}

Extra(){
#### Bat (cat mais bonito.)
url1="https://github.com"
url2=$(wget -qO- "https://github.com/sharkdp/bat/releases" \
	| sed -r '/bat_.*_amd64.deb/!d;s/^.*href="(.*)" rel=.*$/\1/' \
	| sed '1!d')
wget -c "$url1$url2" -P /tmp/ && \
sudo apt install /tmp/bat_*_amd64.deb -y && \
echo -e "$BCor\nInstalacao do Bat!$ECor" && \
echo -e "$Sussesso" || \
echo -e "$Fracasso"

#### LF (File Manager TUI.)
url1="https://github.com"
url2=$(wget -qO- "https://github.com/gokcehan/lf/releases" \
	| sed -r '/linux-amd64/!d;s/^.*href="(.*)" rel=.*$/\1/' \
	| sed '1!d')
wget -c "$url1$url2" -P /tmp/ && \
sudo atool --extract-to="/usr/bin/" /tmp/lf-linux-amd64.tar.gz && \
echo -e "$BCor\nInstalacao do lf!$ECor" && \
echo -e "$Sussesso" || \
echo -e "$Fracasso"

#### NeoVim AppImage.
url1="https://github.com"
url2=$(wget -qO- "https://github.com/neovim/neovim/releases" \
	| sed -r '/\/download\/v[0-9].*nvim.appimage"/!d;s/^.*href="(.*)" rel=.*$/\1/' \
	| sed '1!d')
wget -c "$url1$url2" -O "nvim" && \
chmod +x nvim && \
sudo mv -v nvim /usr/bin/nvim && \
echo -e "$BCor\nInstalacao do NeoVim!$ECor" && \
echo -e "$Sussesso" || \
echo -e "$Fracasso"

#### Instalação do Fuzzy Finder.
git clone --depth 1 https://github.com/junegunn/fzf.git ~/.config/fzf && ~/.config/fzf/install --all && \
echo -e "$BCor\nInstalacao do Fuzzy Finder$ECor" && \
echo -e "$Sussesso" || \
echo -e "$Fracasso"

#### Dragon (drag and drop pelo terminal).
git clone https://github.com/mwh/dragon.git /tmp/dragon && cd /tmp/dragon && make && make install && \
echo -e "$BCor\nInstalacao do Dragon.$ECor" && \
echo -e "$Sussesso" || \
echo -e "$Fracasso"

#### Instalação do Tremc (Transmission-CLI).
git clone https://github.com/tremc/tremc.git /tmp/tremc && cd /tmp/tremc && sudo make install && \
echo -e "$BCor\nInstalacao do Tremc.$ECor" && \
echo -e "$Sussesso" || \
echo -e "$Fracasso"
}

Touchegg(){
#### Touchegg (mais funções no touchpad.)
url1="https://github.com"
url2=$(wget -qO- "https://github.com/JoseExposito/touchegg/releases" \
	| sed -r '/touchegg_.*_amd64.deb/!d;s/^.*href="(.*)" rel=.*$/\1/' \
	| sed '1!d')
wget -c "$url1$url2" -P /tmp/ && \
sudo apt install /tmp/touchegg_*_amd64.deb -y && \
echo -e "$BCor\nInstalacao do Touchegg!$ECor" && \
echo -e "$Sussesso" || \
echo -e "$Fracasso"
}

DockLike(){
Urls=$(wget -qO- "https://launchpad.net/~xubuntu-dev/+archive/ubuntu/extras/+packages?field.name_filter=&field.status_filter=published&field.series_filter=focal" \
	| sed -r '/sprite expander/!d;s/^.*href="(.*)" .*$/https:\/\/launchpad.net\/~xubuntu-dev\/+archive\/ubuntu\/extras\/\1/' \
	| sed ';:a;$!N;s/\n/ /;ta;')
Link=$(eval wget -qO- "$Urls" \
	| sed '/.deb/!d' \
	| sed -r  's/^.*<a href="(.*.deb)">.*$/\1/' \
	| sed '/xfce4-docklike-plugin.*.amd64/!d' \
	| sed '/\.deb$/!d')
eval wget -c "$Link" -P /tmp/DockLike/ && \
sudo apt install /tmp/DockLike/*.deb -y && \
echo -e "$BCor\nInstalacao do DockLike.$ECor" && \
echo -e "$Sussesso" || \
echo -e "$Fracasso"
}

Configs(){
#### Copiar Dotfiles e Plugins.
cp -r -v .config .irssi .bash_aliases .nanorc .tmux.conf .Xresources ~/ && \
echo -e "$BCor\nCopiando arquivos de configuração...$ECor" && \
echo -e "$Sussesso" || \
echo -e "$Fracasso"

#### Papirus MultiCores.
wget -qO- https://git.io/papirus-folders-install | sh && \
echo -e "$BCor\nPapirus Multi-Cores$ECor" && \
echo -e "$Sussesso" || \
echo -e "$Fracasso"

#### Nerd Fonts.
mkdir -vp "$HOME/.local/share/fonts/FiraCode"
url1="https://github.com"
url2=$(wget -qO- "https://github.com/ryanoasis/nerd-fonts/releases" \
	| sed -r '/FiraCode.zip/!d;s/^.*href="(.*)" rel=.*$/\1/' \
	| sed '1!d')
wget -c "$url1$url2" -P /tmp/ && \
atool --extract-to="$HOME/.local/share/fonts/FiraCode" /tmp/FiraCode.zip && \
wget -c \
	"https://github.com/ryanoasis/nerd-fonts/raw/master/patched-fonts/Noto/Emoji/complete/Noto%20Emoji%20Nerd%20Font%20Complete%20Mono.ttf" \
	"https://github.com/ryanoasis/nerd-fonts/raw/master/patched-fonts/Noto/Emoji/complete/Noto%20Emoji%20Nerd%20Font%20Complete.ttf" \
	-P $HOME/.local/share/fonts && \
echo -e "$BCor\nNerd Fonts.$ECor" && \
echo -e "$Sussesso" || \
echo -e "$Fracasso"
}

OpInvalido(){
clear
echo -e "$YCor

	╭────────────────────────╮
	│$RCor   Opção desconhecida.$YCor  │
	╰────────────────────────╯
$ECor"
}

Menu(){
echo -e "$BCor
	1.Sistema
	2.Extra $YCor(Bat, NeoVim, Fuzzy Finder, Dragon, Tremc.)$BCor
	3.DockLike $YCor(Dock para XFCE4-panel.)$BCor
	4.Touchegg $YCor(Mais Funções no TouchPad.)$BCor
	5.Dotfiles
$RCor
	q.Sair
$ECor"
read -r Resposta

case "$Resposta" in
	1)
		Sistema
		Menu ;;
	2)
		Extra
		Menu ;;
	3)
		DockLike
		Menu ;;
	4)
		Touchegg
		Menu ;;
	5)
		Configs
		Menu ;;
	q)
		exit ;;
	*)
		OpInvalido
		Menu ;;
esac
}
Menu
