#!/usr/bin/env bash

#     _    _
#    / \  | | __ _ _ __  _ __      Alann Santos
#   / _ \ | |/ _` | '_ \| '_ \     https://gitlab.com/alannssantos
#  / ___ \| | (_| | | | | | | |
# /_/   \_\_|\__,_|_| |_|_| |_|

## Cores.
RCor="\033[1;31m"    # Red (Vermelho)
GCor="\033[1;32m"    # Green (Verde)
YCor="\033[1;33m"    # Yellow (Amarelo)
BCor="\033[1;34m"    # Blue (Azul)
WCor="\033[1;37m"    # White (Branco)
ECor="\033[0m"       # End (Fim)

## Mensagens

Sussesso="$YCor
╭────────────────────────╮
│$GCor Instalado com sucesso!$YCor │
╰────────────────────────╯
$ECor"
Fracasso="$YCor
╭────────────────────────╮
│  $RCor Erro na instalação!$YCor  │
╰────────────────────────╯
$ECor"

## Funções
Sistema(){
#### Aplicativos e Drivers Pos-instalação.
sudo apt install lf \
	bat \
	exa \
	fzf \
	mpv \
	npm \
	cups \
	curl \
	lynx \
	peek \
	slop \
	tmux \
	atool \
	cmake \
	sshfs \
	xclip \
	mcomix \
        neovim \
	xinput \
	blueman \
	concalc \
	flatpak \
	gparted \
	w3m-img \
	xdotool \
	xsensors \
	arc-theme \
	keepassxc \
	pkg-config \
	streamlink \
	zlib1g-dev \
	simple-scan \
	python3-dev \
	libxtst-dev \
	font-manager \
	python3-full \
	libgtk-3-dev \
        gvfs-backends \
	poppler-utils \
	fonts-firacode \
	network-manager \
	libfreetype6-dev \
	libxkbcommon-dev \
	paper-icon-theme \
	ffmpegthumbnailer \
	libfontconfig1-dev \
	libxcb-xfixes0-dev \
	papirus-icon-theme \
	python3-libtorrent \
	printer-driver-all \
	breeze-cursor-theme \
	libjpeg62-turbo-dev \
	libimage-exiftool-perl -y && \

sudo apt update && \
sudo apt upgrade -y && \
sudo flatpak remote-add flathub https://flathub.org/repo/flathub.flatpakrepo && \
npm config set prefix "$HOME/.local" && \
python3 -m venv "$HOME/.local" && \
pip3 install jedi && \
pip3 install stig && \
pip3 install pyperclip && \
pip3 install epy-reader && \
pip3 install gallery-dl && \
pip3 install subliminal && \
pip3 install youtube-dl && \
pip3 install transmission-rpc && \
echo -e "$BCor\nSistema!$ECor" && \
echo -e "$Sussesso" || \
echo -e "$Fracasso"
}

Configs(){
#### Copiar Dotfiles e Plugins.
cp -r -v .config .irssi .bash_aliases .nanorc .tmux.conf .Xresources ~/ && \
echo -e "$BCor\nCopiando arquivos de configuração...$ECor" && \
echo -e "$Sussesso" || \
echo -e "$Fracasso"

#### Nerd Fonts.
mkdir -vp "$HOME/.local/share/fonts/FiraCode"
url1=$(wget -qO- "https://github.com/ryanoasis/nerd-fonts/releases" \
	| sed -r '/h2 class/!d;s/^.*">(.*)<\/.*/\1/' \
	| sed '1!d')
wget -c "https://github.com/ryanoasis/nerd-fonts/releases/download/$url1/FiraCode.zip" -P /tmp/ && \
atool --extract-to="$HOME/.local/share/fonts/FiraCode" /tmp/FiraCode.zip && \
echo -e "$BCor\nNerd Fonts.$ECor" && \
echo -e "$Sussesso" || \
echo -e "$Fracasso"
}

OpInvalido(){
clear
echo -e "$YCor

	╭────────────────────────╮
	│$RCor   Opção desconhecida.$YCor  │
	╰────────────────────────╯
$ECor"
}

Menu(){
echo -e "$BCor
	1.Sistema
	2.Dotfiles
$RCor
	q.Sair
$ECor"
read -r Resposta

case "$Resposta" in
	1)
		Sistema
		Menu ;;
	2)
		Configs
		Menu ;;
	q)
		exit ;;
	*)
		OpInvalido
		Menu ;;
esac
}
Menu
