#!/usr/bin/env bash

file="$(file --mime-type --dereference --brief "$1")"
mimetype="$(mimetype --dereference --brief --mimetype -- "$1")"

handler_image(){
  [ "$1" == '--' ] && shift

  function abspath {
    case "$1" in
      /*) printf "%s\n" "$1";;
      *)  printf "%s\n" "$PWD/$1";;
    esac
  }
  function listfiles {
    find -L "$(dirname "$target")" -maxdepth 1 -type f -iregex \
      '.*\(jpe?g\|bmp\|png\|gif\)$' -print0 | sort -z
  }

  target="$(abspath $1)"
  count="$(listfiles | grep -m 1 -Zznx "$target" | cut -d: -f1)"

  if [ -n "$count" ]; then
    listfiles | xargs -0 feh -. -B black -g 640x480 --start-at "$target" --
  else
    feh -. -B black -g 640x480 -- "$@" # fallback
  fi
}

handler_comic(){
  mcomix "$1" &
}

handler_torrent(){
  transmission-remote -a "$1"
}

handler_pdf(){
  zathura "$1" &
}

handler_audio(){
  mpv "$1"
}

handler_video(){
  nohup mpv --fs "$1" >/dev/null &
}

handler_text(){
  nvim "$1"
}

if grep -q "^text" <<< "$file"
then mimetype="$file"
fi

case $mimetype in
  */pdf) handler_pdf "$1" ;;

  video/*) handler_video "$1" ;;

  audio/*) handler_audio "$1" ;;

  image/*) handler_image "$1" ;;

  text/* |\
    */json) handler_text "$1" ;;

  */x-bittorrent) handler_torrent "$1" ;;

  */vnd.comicbook+zip |\
    */vnd.comicbook-rar) handler_comic "$1" ;;
esac
