#!/usr/bin/env bash

old="$(mktemp)"
new="$(mktemp)"
printf '%s\n' "$@" | sed 's/.*\///' >"$old"
printf '%s\n' "$@" | sed 's/.*\///' >"$new"
# nvim "$new"
helix "$new"
[ "$(wc -l < "$new")" -ne "$(wc -l < "$old")" ] && exit
  paste "$old" "$new" | while IFS= read -r names; do
    src="$(printf '%s' "$names" | cut -f1)"
    dst="$(printf '%s' "$names" | cut -f2)"
    if [ "$src" = "$dst" ] || [ -e "$dst" ]; then
      continue
    fi
      mv -- "$src" "$dst"
    done
    rm -- "$old" "$new"
    lf -remote "send $id unselect"
