#!/usr/bin/env bash

res="$(find . /home /media /mnt 2>/dev/null | fzf -e --prompt='Ir Para: ')"
if [ -f "$res" ]; then
  cmd="select"
elif [ -d "$res" ]; then
  cmd="cd"
fi
lf -remote "send $id $cmd \"$res\""
