#!/usr/bin/env bash

# handling files name.
files=$(printf '%s\n' "$@" | sed 's/.*\//"/;s/$/" /' | sed ':a;$!N;s/\n//;ta;')

# sort file type.
file="$(eval file --mime-type --dereference --brief "$files")"
mimetype="$(eval mimetype --dereference --brief --mimetype -- "$files")"

handler_image(){
  [ "$1" == '--' ] && shift

  function abspath {
    case "$1" in
      /*) printf "%s\n" "$1";;
      *)  printf "%s\n" "$PWD/$1";;
    esac
  }
  function listfiles {
    find -L "$(dirname "$target")" -maxdepth 1 -type f -iregex \
      '.*\(jpe?g\|bmp\|png\|gif\)$' -print0 | sort -z
  }

  target="$(abspath "$1")"
  count="$(listfiles | grep -m 1 -Zznx "$target" | cut -d: -f1)"

  if [ -n "$count" ]; then
    listfiles | xargs -0 feh -. -B black -g 640x480 --start-at "$target" --
  else
    feh -. -B black -g 640x480 -- "$@" # fallback
  fi
}

handler_comic(){
  mcomix "$1" &
}

handler_torrent(){
  transmission-remote -a "$1"
}

handler_pdf(){
  eval zathura "$files" &
}

handler_audio(){
  mpv --no-video "$1"
}

handler_video(){
  nohup mpv --fs "$1" >/dev/null 2>&1 &
}

handler_text(){
  eval nvim -p "$files"
}

handler_ebook(){
  epy "$1"
}

handler_keepass(){
  keepassxc "$1" 2>/dev/null &
}

handler_xdg-open(){
  xdg-open "$1" 2>/dev/null &
}

if grep -q "^text" <<< "$file"
then mimetype="$file"
fi

case $mimetype in
  */pdf) handler_pdf "$@" ;;

  video/*) handler_video "$@" ;;

  audio/*) handler_audio "$@" ;;

  image/*) handler_image "$@" ;;

  text/* |\
    */json) handler_text "$@" ;;

  */x-keepass2) handler_keepass "$@" ;;

  */x-bittorrent) handler_torrent "$@" ;;

  */vnd.comicbook+zip |\
    */vnd.comicbook-rar) handler_comic "$@" ;;

  */epub+zip |\
    */x-mobipocket-ebook) handler_ebook "$@" ;;

  *) handler_xdg-open "$@" ;;
esac
