#!/usr/bin/env bash

# handling files name.
files=$(printf '%s\n' "$@" | sed 's/.*\//"/;s/$/" /' | sed ':a;$!N;s/\n//;ta;')

# sort file type.
file="$(eval file --mime-type --dereference --brief "$files")"
mimetype="$(eval mimetype --dereference --brief --mimetype -- "$files")"

handler_image(){
  gwenview "$1" >/dev/null 2>&1 &
}

handler_comic(){
  mcomix "$1" &
}

handler_torrent(){
  transmission-remote -a "$1"
}

handler_pdf(){
  eval zathura "$files" &
}

handler_audio(){
  mpv --no-video "$1"
}

handler_video(){
  nohup mpv --fs "$1" >/dev/null 2>&1 &
}

handler_text(){
  eval helix "$files"
}

handler_ebook(){
  epy "$1"
}

handler_keepass(){
  keepassxc "$1" 2>/dev/null &
}

handler_xdg-open(){
  xdg-open "$1" 2>/dev/null &
}

if grep -q "^text" <<< "$file"
then mimetype="$file"
fi

case $mimetype in
  */pdf) handler_pdf "$@" ;;

  video/*) handler_video "$@" ;;

  audio/*) handler_audio "$@" ;;

  image/*) handler_image "$@" ;;

  text/* |\
    */json) handler_text "$@" ;;

  */x-keepass2) handler_keepass "$@" ;;

  */x-bittorrent) handler_torrent "$@" ;;

  */vnd.comicbook+zip |\
    */vnd.comicbook-rar) handler_comic "$@" ;;

  */epub+zip |\
    */x-mobipocket-ebook) handler_ebook "$@" ;;

  *) handler_xdg-open "$@" ;;
esac
