tasks:
  # Remove torrent depois de Upar o dobro!
  clean-transmission:
    disable: [seen, seen_info_hash]
    accept_all: yes
    from_transmission:
      only_complete: yes
    if:
      - transmission_ratio < 1.0: reject
    transmission:
      action: remove
  # RSS
  Mangas:
    sequence:
      - rss: http://fanfox.net/rss/kanojo_okarishimasu.xml #Kanojo, Okarishimasu
      - rss: http://fanfox.net/rss/boku_no_hero_academia.xml #Boku no Hero Academia
      - rss: http://fanfox.net/rss/enen_no_shouboutai.xml #Enen no Shouboutai
      - rss: http://fanfox.net/rss/gleipnir.xml #Gleipnir
      - rss: http://fanfox.net/rss/jagaaaaaan.xml #Jagaaaaaan
      - rss: http://fanfox.net/rss/black_clover.xml #Black Clover
      - rss: http://fanfox.net/rss/parallel_paradise.xml #Parallel Paradise
      - rss: http://fanfox.net/rss/mato_seihei_no_slave.xml #Mato Seihei no Slave
      - rss: http://fanfox.net/rss/berserk_of_gluttony.xml #Berserk of Gluttony
      - rss: http://fanfox.net/rss/the_story_between_a_dumb_prefect_and_a_high_school_girl_with_an_inappropriate_skirt_length.xml #The Story Between a Dumb Prefect and a High School Girl with an Inappropriate Skirt Length
    accept_all: yes
    exec: ~/.local/bin/gallery-dl -d /tmp/ --exec-after 'cd {}/.. && zip -rm ~/HardDisk/Plex/Mangas/Weekly/"{{title}}".cbz *' {{url}}
  Animes:
    sequence:
      - rss: https://nyaa.si/?page=rss&q=megalo+box+Multiple+Subtitle+720p+v0&c=1_2&f=2
    regexp:
      accept:
        - (\[Multiple Subtitle\]|\[720p\]).*(\[Multiple Subtitle\]|\[720p\])
    transmission:
      host: localhost
      port: 9091
      username: ""
      password: ""
      path: "/media/HardDisk/Plex/Animes/Megalo Box 2"
  Series:
    discover:
      what:
        - next_series_episodes: yes
      from:
        - 1337x: yes
      interval: 30 minutes
    series:
      settings:
        shows:
          quality: 720p
          propers: no
      shows:
        - Westworld:
            begin: S04E01
        - Motherland Fort Salem:
            begin: S02E01
        - Lovecraft Country:
            begin: S02E01
        - The Boys:
            begin: S03E01
        - American Gods:
            begin: S04E01
        - Carnival Row:
            begin: S02E01
    transmission:
      host: localhost
      port: 9091
      username: ""
      password: ""
      path: /media/HardDisk/Plex/Series

  # Filmes adcionado com `flexget movie_list add [nome do filme|id_imdb]`
  Filmes:
    discover:
      what:
        - movie_list: movies
      from:
        - yts: yes
      interval: 30 minutes
    list_match:
      from:
        - movie_list: movies
    quality:
      - 1080p
      - bluray|webrip
    imdb_lookup: yes
    transmission:
      host: localhost
      port: 9091
      username: ""
      password: ""
      path: /media/HardDisk/Plex/Filmes
  Legendas:
    filesystem:
      path:
        - /media/HardDisk/Plex/Series
        - /media/HardDisk/Plex/Filmes
      regexp: '.*\.(avi|mkv|mp4)$'
      recursive: yes
    accept_all: yes
    seen: local
    subliminal:
      languages:
        - pt-BR
      alternatives:
        - en
      exact_match: no
      single: no
      hearing_impaired: yes
      authentication:
        opensubtitles:
          username: LOGIN
          password: PASSWORD
