tasks:
  # Remove torrent depois de Upar o dobro!
  clean-transmission:
    disable: [seen, seen_info_hash]
    accept_all: yes
    from_transmission:
      only_complete: yes
    if:
      - transmission_ratio < 1.0: reject
    transmission:
      action: remove
  # RSS
  Mangas:
    sequence:
      - rss: http://fanfox.net/rss/kanojo_okarishimasu.xml #Kanojo, Okarishimasu
      - rss: http://fanfox.net/rss/boku_no_hero_academia.xml #Boku no Hero Academia
      - rss: http://fanfox.net/rss/enen_no_shouboutai.xml #Enen no Shouboutai
      - rss: http://fanfox.net/rss/gleipnir.xml #Gleipnir
      - rss: http://fanfox.net/rss/jagaaaaaan.xml #Jagaaaaaan
      - rss: http://fanfox.net/rss/black_clover.xml #Black Clover
      - rss: http://fanfox.net/rss/parallel_paradise.xml #Parallel Paradise
      - rss: http://fanfox.net/rss/mato_seihei_no_slave.xml #Mato Seihei no Slave
      - rss: http://fanfox.net/rss/berserk_of_gluttony.xml #Berserk of Gluttony
      - rss: http://fanfox.net/rss/the_story_between_a_dumb_prefect_and_a_high_school_girl_with_an_inappropriate_skirt_length.xml #The Story Between a Dumb Prefect and a High School Girl with an Inappropriate Skirt Length
    accept_all: yes
    exec: ~/.local/bin/gallery-dl -d /tmp/ --exec-after 'cd {}/.. && zip -rm ~/HardDisk/Plex/Mangas/Weekly/"{{title}}".cbz *' {{url}}
  Animes:
    sequence:
      - rss: https://nyaa.si/?page=rss&q=megalo+box+Multiple+Subtitle+720p+v0&c=1_2&f=2
    regexp:
      accept:
        - (\[Multiple Subtitle\]|\[720p\]).*(\[Multiple Subtitle\]|\[720p\])
    transmission:
      host: localhost
      port: 9091
      username: ""
      password: ""
      path: "/home/alann/HardDisk/Plex/Animes/Megalo Box 2"
  Filmes:
    rss: https://yts.mx/rss/0/1080p/all/0/en
    imdb_lookup: yes
    list_match:
      from:
        - movie_list: movies
    transmission:
      host: localhost
      port: 9091
      username: ""
      password: ""
      path: /media/Stronger/Emby/Filmes
  Series:
    sequence:
      - rss: https://showrss.info/show/651.rss #Westworld
      - rss: https://showrss.info/show/1296.rss #Motherland: Fort Salem
      - rss: https://showrss.info/show/1338.rss #Lovecraft Country
      - rss: https://showrss.info/show/1183.rss #The Boys
      - rss: https://showrss.info/show/810.rss #American Gods
      - rss: https://showrss.info/show/1193.rss #Carnival Row
      - rss: https://showrss.info/show/1388.rss #WandaVision
      - rss: https://showrss.info/show/1401.rss #Superman & Lois
    regexp:
      accept:
        - (1080p)
      reject:
        - (Repack|PROPER)
    transmission:
      host: localhost
      port: 9091
      username: ""
      password: ""
      path: /media/Stronger/Emby/Series
