tasks:
  # Remove torrent depois de Upar a mesma quantidade!
  Limpeza:
    disable: [seen, seen_info_hash]
    accept_all: yes
    from_transmission:
      only_complete: yes
    if:
      - transmission_ratio < 1.0: reject
    transmission:
      action: pause

  # RSS
  Mangas:
    sequence:
      - rss: http://fanfox.net/rss/gleipnir.xml
      - rss: http://fanfox.net/rss/jagaaaaaan.xml
      - rss: http://fanfox.net/rss/black_clover.xml
      - rss: http://fanfox.net/rss/parallel_paradise.xml
      - rss: http://fanfox.net/rss/enen_no_shouboutai.xml
      - rss: http://fanfox.net/rss/berserk_of_gluttony.xml
      - rss: http://fanfox.net/rss/kanojo_okarishimasu.xml
      - rss: http://fanfox.net/rss/mato_seihei_no_slave.xml
      - rss: http://fanfox.net/rss/boku_no_hero_academia.xml
    accept_all: yes
    exec: ~/.local/bin/gallery-dl -d /tmp/ --exec-after 'cd {}/.. && zip -rm ~/HardDisk/Plex/Mangas/Weekly/"{{title}}".cbz *' {{url}}
  Comics:
    sequence:
      - rss: https://torrentgalaxy.mx/rss?user=2918
    accept_all: yes
    transmission:
      host: localhost
      port: 9091
      username: ""
      password: ""
      path: "/media/HardDisk/Plex/HQ's/Weekly"
  Animes:
    discover:
      what:
        - next_series_episodes: yes
      from:
        - nyaa:
            category: "anime eng"
            filter: "trusted only"
      interval: 15 minutes
      release_estimations: ignore
    series:
      settings:
        shows:
          quality: 720p+
          exact: yes
      shows:
        - "Nomad - Megalo Box 2":
            from_group: Erai-raws
            begin: 01
    transmission:
      host: localhost
      port: 9091
      username: ""
      password: ""
      path: "/media/HardDisk/Plex/Animes/{{series_name}}/"
  Series:
    discover:
      what:
        - next_series_episodes: yes
      from:
        - rarbg: {ranked: True}
      interval: 15 minutes
    series:
      settings:
        shows:
          quality: 720p
          propers: no
          exact: yes
      shows:
        - Westworld:
            begin: S04E01
        - Motherland Fort Salem:
            begin: S02E01
        - Lovecraft Country:
            begin: S02E01
        - The Boys:
            begin: S03E01
        - American Gods:
            begin: S04E01
        - Carnival Row:
            begin: S02E01
        - Loki:
            begin: S01E01
        - Arcane:
            begin: S01E01
        - Evil:
            begin: S02E01
    transmission:
      host: localhost
      port: 9091
      username: ""
      password: ""
      path: "/media/HardDisk/Plex/Series/{{series_name}}/Season {{series_season}}/"

  # Filmes adcionado com `flexget movie_list add [nome do filme|id_imdb]`
  Filmes:
    discover:
      what:
        - movie_list: movies
      from:
        - yts: yes
      interval: 15 minutes
    list_match:
      from:
        - movie_list: movies
    quality:
      - 1080p
      - bluray|webrip
    imdb_lookup: yes
    transmission:
      host: localhost
      port: 9091
      username: ""
      password: ""
      path: /media/HardDisk/Plex/Filmes
  Legendas:
    filesystem:
      path:
        - /media/HardDisk/Plex/Series
        - /media/HardDisk/Plex/Filmes
      regexp: '.*\.(avi|mkv|mp4)$'
      recursive: yes
    accept_all: yes
    seen: local
    subliminal:
      languages:
        - pt-BR
      exact_match: no
      single: no
      hearing_impaired: yes
      authentication:
        opensubtitles:
          username: LOGIN
          password: PASSWORD
