# Transmission só funciona com `pip3 install transmission-rpc`.
# Series só funciona com `pip3 install cloudscraper`.
# Mais informações `https://flexget.com/Plugins/transmission`.
tasks:
  ################################################################
  # Animes colocados automaticamente pelo MAL(MyAnimeList).
  # Animes:
  #   discover:
  #     what:
  #       - next_series_episodes:
  #           from_start: yes
  #     from:
  #       - nyaa:
  #           category: "anime"
  #           filter: "all"
  #     interval: 15 minutes
  #     release_estimations: ignore
  #   configure_series:
  #     settings:
  #       identified_by: sequence
  #       from_group:
  #         - PT-BR
  #         - POR-BR
  #       quality: 720p-1080p
  #       propers: 2 days
  #     from:
  #       my_anime_list:
  #         username: <<username>>
  #         status:
  #           - watching
  #           - plan_to_watch
  #         airing_status:
  #           - airing
  #           - planned
  #         type: tv
  #   tvmaze_lookup: yes
  #   qbittorrent:
  #     host: localhost
  #     port: 8080
  #     path: "/media/HardDisk/Jellyfin/Animes/{{series_name}}/"

  ################################################################
  # Animes colocados manualmente
  Animes:
    discover:
      what:
        - next_series_episodes: yes
      from:
        - nyaa:
            category: "anime"
            filter: "all"
      interval: 15 minutes
      release_estimations: ignore
    series:
      settings:
        shows:
          quality: 720p-1080p
          propers: 2 days
          from_group:
            - DKB
      shows:
        # Fall
        - "Dan Da Dan":
            begin: 07
            from_group:
              - Erai-raws
        - "MF Ghost 2nd Season":
            begin: 06
            path: "/media/HardDisk/Jellyfin/Animes/MF Ghost/Season 02/"
            from_group:
              - DKB
    thetvdb_lookup: yes
    qbittorrent:
      host: localhost
      port: 8080
      path: "/media/HardDisk/Jellyfin/Animes/{{series_name}}/"
      label: animes
      tags:
        - flexget-animes

  ################################################################
  Series:
    discover:
      what:
        - next_series_seasons: yes
        - next_series_episodes: yes
      from:
        - 1337x: yes
      interval: 15 minutes
      release_estimations: loose
    content_size:
      min: 900 MiB
      strict: no
    series:
      settings:
        shows:
          from_group:
            - TGx
            - FLUX
            - TURG
          quality: 1080p
          propers: 2 days
          season_packs: yes
      shows:
        - "Gen V":
            begin: S02E01
        - "From":
            exact: yes
            begin: S04E01
    thetvdb_lookup: yes
    qbittorrent:
      host: localhost
      port: 8080
      path: "/media/HardDisk/Jellyfin/Series/{{series_name}}/Season {{series_season}}/"
      label: tv-shows
      tags:
        - flexget-series

  ################################################################
  # Filmes adcionado com `flexget movie_list add (nome do filme|id_imdb)`
  # Filmes:
  #   discover:
  #     what:
  #       - movie_list: movies
  #     from:
  #       - yts: yes
  #     interval: 15 minutes
  #     release_estimations: ignore
  #   list_match:
  #     from:
  #       - movie_list: movies
  #   quality:
  #     - 1080p
  #     - bluray|webrip
  #   imdb_lookup: yes
  #   qbittorrent:
  #     host: localhost
  #     port: 8080
  #     path: /media/HardDisk/Plex/Filmes
