# Para a notificação via telegram funcionar é preciso colocar o <TokenID> e <UserName>.
# Crie um Bot para gerar um TokenID e inicie uma conversa com ele para gerar ChatID,
# caso voce não tenha um UserName vá nas configurações do telegram e crie.
# Instalar `pip3 install python-telegram-bot==12.8`.
templates:
  global:
    notify:
      entries:
        message:
          |+
          {% if series_name is defined -%}
          *{{series_name}}* - {{series_id}}
          *{{tvmaze_episode_name|d(tvdb_ep_name)|d('')}}*
          [Image]({{tvmaze_series_original_image|replace("_", "%5F")}})
          {% elif imdb_name is defined -%}
          *{{imdb_name}}* - ({{imdb_year}})
          [Image]({{(tvdb_posters|d|first )|d(imdb_photo)|d|replace("_", "%5F")}})
          {% else -%}
          {{title}}
          {%- endif -%}
        via:
          - telegram:
              bot_token: '<TokenID>'
              parse_mode: markdown
              disable_previews: no
              recipients:
                - username: '<UserName>'

# Transmission só funciona com `pip3 install transmission-rpc`.
# Mais informações `https://flexget.com/Plugins/transmission`.
tasks:
  # Remove torrent depois de Upar a mesma quantidade!
  Limpeza:
    disable: [seen, seen_info_hash]
    accept_all: yes
    from_transmission:
      only_complete: yes
    if:
      - transmission_ratio < 1.0: reject
    transmission:
      action: remove
    template: no_global

  # Baixar mangas do (mangafox|fanfox) só funciona com `pip3 install gallery-dl`.
  Mangas:
    sequence:
      - rss: http://fanfox.net/rss/gleipnir.xml
      - rss: http://fanfox.net/rss/jagaaaaaan.xml
      - rss: http://fanfox.net/rss/black_clover.xml
      - rss: http://fanfox.net/rss/killing_bites.xml
      - rss: http://fanfox.net/rss/parallel_paradise.xml
      - rss: http://fanfox.net/rss/enen_no_shouboutai.xml
      - rss: http://fanfox.net/rss/berserk_of_gluttony.xml
      - rss: http://fanfox.net/rss/kanojo_okarishimasu.xml
      - rss: http://fanfox.net/rss/mato_seihei_no_slave.xml
      - rss: http://fanfox.net/rss/boku_no_hero_academia.xml
      - rss: http://fanfox.net/rss/ren_ai_shikou_seitokai.xml
      - rss: http://fanfox.net/rss/amano_megumi_wa_suki_darake.xml
      - rss: http://fanfox.net/rss/hitomi_chan_is_shy_with_strangers.xml
    accept_all: yes
    exec:
      - echo "|$(date '+%d/%m/%Y %H:%M:%S')|{{title}}|Mangas|" >> ~/Flexget-Update.md
      - ~/.local/bin/gallery-dl -d /tmp/ --exec-after 'cd {}/.. && zip -rm ~/HardDisk/Plex/Mangas/Weekly/"{{title}}".cbz *' {{url}}
  Comics:
    sequence:
      - rss: https://torrentgalaxy.mx/rss?user=2918
    accept_all: yes
    transmission:
      host: localhost
      port: 9091
      username: ""
      password: ""
      path: "/media/HardDisk/Plex/HQ's/Weekly"
    exec:
      - echo "|$(date '+%d/%m/%Y %H:%M:%S')|{{title}}|Comics|" >> ~/Flexget-Update.md
  Animes:
    discover:
      what:
        - next_series_episodes: yes
      from:
        - nyaa:
            category: "anime eng"
            filter: "trusted only"
      interval: 15 minutes
      release_estimations: ignore
    series:
      settings:
        shows:
          quality: 720p+
      shows:
        - "Nomad - Megalo Box 2":
            from_group: Erai-raws
            begin: 14
    tvmaze_lookup: yes
    transmission:
      host: localhost
      port: 9091
      username: ""
      password: ""
      path: "/media/HardDisk/Plex/Animes/{{series_name}}/"
    exec:
      - echo "|$(date '+%d/%m/%Y %H:%M:%S')|{{series_name}}|Animes|" >> ~/Flexget-Update.md
  Series:
    discover:
      what:
        - next_series_episodes: yes
      from:
        - rarbg: {ranked: True}
      interval: 15 minutes
    series:
      settings:
        shows:
          quality: 720p+
      shows:
        - Westworld:
            begin: S04E01
        - Motherland Fort Salem:
            begin: S02E01
        - Lovecraft Country:
            begin: S02E01
        - The Boys:
            begin: S03E01
        - American Gods:
            begin: S04E01
        - Carnival Row:
            begin: S02E01
        - Loki:
            begin: S02E01
        - Arcane:
            begin: S02E01
            exact: yes
        - The Witcher:
            begin: S02E01
        - What If...?:
            begin: S02E01
    tvmaze_lookup: yes
    transmission:
      host: localhost
      port: 9091
      username: ""
      password: ""
      path: "/media/HardDisk/Plex/Series/{{series_name}}/Season {{series_season}}/"
    exec:
      - echo "|$(date '+%d/%m/%Y %H:%M:%S')|{{series_name}}|Series|" >> ~/Flexget-Update.md

  # Filmes adcionado com `flexget movie_list add (nome do filme|id_imdb)`
  Filmes:
    discover:
      what:
        - movie_list: movies
      from:
        - yts: yes
      interval: 15 minutes
    list_match:
      from:
        - movie_list: movies
    quality:
      - 1080p
      - bluray|webrip
    imdb_lookup: yes
    transmission:
      host: localhost
      port: 9091
      username: ""
      password: ""
      path: /media/HardDisk/Plex/Filmes
    exec:
      - echo "|$(date '+%d/%m/%Y %H:%M:%S')|{{imdb_name}}|Filmes|" >> ~/Flexget-Update.md
