#!/usr/bin/env bash

Bookmarks=~/.favoritos
Browser="firefox"
Fzfopt="fzf -e --color=16 --tiebreak=begin -i"

# Pegar favoritos do Firefox Automaticamente.
#
# Abra o Firefox e digite na barra de endereço "about:config".
# Pesquise por "browser.bookmarks.autoExportHTML" mude para "true".
# Pesquise por "browser.bookmarks.file" escolha texto e adicione "~/.favoritos".
#

Site=$(sed -r '/http/!d;s/^.*HREF="(.*)" ADD_DATE=.*">(.*)<\/A>.*$/\2𤭢┃\1/' $Bookmarks \
	| column -t -s "𤭢" \
	| $Fzfopt \
	| sed 's/#Porn.*┃\|#Hentai.*┃/┃--private-window /' \
	| sed 's/^.*┃//')

if [ -n "$Site" ]; then
	eval $Browser "$Site" &
fi
