#!/usr/bin/env bash

Navegador="firefox"
bookmark_orig="$HOME/.mozilla/.librewolf/q7vhms2b.default-default/places.sqlite"
bookmark_file="/tmp/places.sqlite"

sql="select moz_places.url, moz_bookmarks.title
     from moz_places, moz_bookmarks
     where moz_bookmarks.fk = moz_places.id
     and moz_bookmarks.type = 1
     and length(moz_bookmarks.title) > 0
     order by moz_bookmarks.dateAdded"

cp $bookmark_orig $bookmark_file

Resposta=$(sqlite3 "$bookmark_file" "$sql" |
  sed 's/|/𤭢/' |
  fzf -e -m --border --margin=20% --delimiter '𤭢' --with-nth='2..' --prompt=Bookmarks: |
  sed -r 's/^(.*)𤭢.*#Porn.*|^(.*)𤭢.*#Hentai.*/--private-window \1\2/' |
  sed 's/𤭢.*//')

if [ -n "$Resposta" ]; then
  eval "$Navegador $Resposta" &
fi
