#!/usr/bin/env bash

Fzfopt='fzf -e --color='fg+:#99cc99,pointer:#99cc99,prompt:#99cc99,border:#99cc99' --layout=reverse-list --margin=20% --border --no-info --phony'

Escolha=$(echo -e "Escolha a uma das opções.

Desligar
Reiniciar
Suspender

Sair"	| $Fzfopt | sed 's/ .*$//')

case "$Escolha" in
	Desligar)
		systemctl poweroff;;
	Reiniciar)
		systemctl reboot;;
	Suspender)
		systemctl suspend;;
	Sair)
		exit;;
esac
