#!/usr/bin/env bash

Escolha=$(echo -e "Escolha a uma das opções.

Desligar
Reiniciar
Suspender

Sair" \
	| fzf -e \
		--layout=reverse-list \
		--color='fg:#99cc99,fg+:#2d2d2d,bg+:#99cc99,pointer:#2d2d2d,prompt:#99cc99' \
		--no-info \
		--phony \
	| sed 's/ .*$//')

case "$Escolha" in
	Desligar)
		systemctl poweroff;;
	Reiniciar)
		systemctl reboot;;
	Suspender)
		systemctl suspend;;
	Sair)
		exit;;
esac
