#!/usr/bin/env bash

Bookmarks=~/.favoritos
Browser="firefox"

# Pegar favoritos do Firefox Automaticamente.
#
# Abra o Firefox e digite na barra de endereço "about:config".
# Pesquise por "browser.bookmarks.autoExportHTML" mude para "true".
# Pesquise por "browser.bookmarks.file" escolha texto e adicione "~/.favoritos".
#

if [ "$@" ]; then
	eval $Browser "$(echo "$@" \
		| sed 's/#Porn.*┃\|#Hentai.*┃/┃--private-window /' \
		| sed 's/^.*┃//')" &
else
	sed -r '/http/!d;s/^.*HREF="(.*)" ADD_DATE=.*">(.*)<\/A>.*$/\2𤭢┃\1/' $Bookmarks \
		| column -t -s "𤭢"
fi

